# Generated by Django 4.0.3 on 2022-04-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
        ('accounts', '0002_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.preference')),
            ],
        ),
    ]
