# Generated by Django 4.0.3 on 2022-03-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering', models.CharField(default='', max_length=255)),
                ('flower_presence', models.CharField(default='', max_length=255)),
                ('manage_difficulty', models.CharField(default='', max_length=255)),
                ('growth_rate', models.CharField(default='', max_length=255)),
                ('placement', models.CharField(default='', max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
