# Generated by Django 4.0.3 on 2022-03-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birthday_user_gender_user_nickname_and_more'),
        ('accounts', '0003_remove_user_birthday_remove_user_gender_and_more'),
    ]

    operations = [
    ]
