# Generated by Django 4.0.3 on 2022-04-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preferplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferplant',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferPlant', to='accounts.preference'),
        ),
    ]
