version: "3.8"

services:
  front:
    build: ./frontend/
    restart: always
    environment:
      TZ: Asia/Seoul
    expose:
      - "3000"
    networks:
      - default
  back:
    build: ./backend/
    command: >
      bash -c "
      ./wait-for-it.sh db:3306 -t 3
      && python manage.py makemigrations 
      && python manage.py migrate --settings=forest.settings.prod
      && gunicorn forest.wsgi --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=forest.settings.prod
      "
    restart: always
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./backend:./
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - default
  db:
    image: mysql:8
    platform: linux/x86_64
    restart: always
    environment:
      TZ: Asia/Seoul
    env_file: ./docker/db/.env
    volumes:
      # - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    external:
      name: forest_net
