version: "3.8"

services:
  nginx_proxy:
    build: ./docker/nginx/
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - default
  front:
    build: ./frontend/
    restart: always
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    networks:
      - default
  back:
    build: ./backend/
    restart: always
    environment:
      TZ: Asia/Seoul
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
  db:
    image: mysql:8
    platform: linux/x86_64
    restart: always
    environment:
      TZ: Asia/Seoul
    env_file: ./docker/db/.env
    volumes:
      # - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    external:
      name: forest_net
