version: "3.8"

services:
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
  nginx_proxy:
    build: ./docker/nginx/
    restart: always
    volumes:
      - ./backend/media:/home/media
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

networks:
  default:
    external:
      name: forest_net
