# Generated by Django 4.0.3 on 2022-04-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=50, null=True, upload_to='images/posts/'),
        ),
    ]
