# Generated by Django 4.0.3 on 2022-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='profile_image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
