# Generated by Django 4.0.3 on 2022-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_name_alter_store_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/stores/'),
        ),
    ]
