# Generated by Django 4.0.3 on 2022-03-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/plants/')),
                ('character', models.TextField(default='', null=True)),
                ('watering', models.TextField(default='', null=True)),
                ('light_demand', models.CharField(default='', max_length=255, null=True)),
                ('humidity', models.CharField(default='', max_length=50, null=True)),
                ('flower_presence', models.CharField(default='', max_length=3, null=True)),
                ('flower_color', models.CharField(default='', max_length=50, null=True)),
                ('manage_difficulty', models.CharField(default='', max_length=50, null=True)),
                ('winter_minimum_temperature', models.CharField(default='', max_length=50, null=True)),
                ('growth_rate', models.CharField(default='', max_length=50, null=True)),
                ('placement', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
