# Generated by Django 4.0.3 on 2022-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_image_path_alter_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='character',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_presence',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_rate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='huumidity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_demand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='manage_defficulty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='placement',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='winter_minimum_temperature',
            field=models.CharField(default='', max_length=50),
        ),
    ]
