# Generated by Django 4.0.3 on 2022-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_plant_character_plant_flower_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/plants/'),
        ),
    ]
