# Generated by Django 4.0.3 on 2022-03-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('open_date', models.DateField(max_length=50)),
                ('close_date', models.DateField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
