# Generated by Django 4.0.3 on 2022-03-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_plant_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
