# Generated by Django 4.0.3 on 2022-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
